### ISSUE TITLE
dmsvg not processing certain flats.

### ISSUE THREAD

**Issue by bcahue** [devinacker/dmsvg#1]
Hello, I was excited to see this project as I intended to use this utility for a pipeline to get wad svgs in order to generate overlays on top, but noticed certain maps on certain WADs did not draw flats. An example is this map:

https://wads.doomleague.org/wdl2020.wad_MAP04.svg

Another example from the same wad:

https://wads.doomleague.org/wdl2020.wad_MAP22.svg

Location of this wad is here:

https://wads.doomleague.org/wdl2020.zip

**Comment by devinacker** [comment]
Hmm, are you sure you're using the most up to date version of the script? Those look like it's not generating the alpha mask 100% correctly, which is a thing I ended up fixing a couple of times when I was originally working on it before.

Here's how they come out on my end:
https://revenant1.net/dmsvg/examples/wdlmap04.svg
https://revenant1.net/dmsvg/examples/wdlmap22.svg

**Comment by bcahue** [comment]
I was using the py2exe executable from the 2020-04-30 release to generate these on Windows, so I checked out the latest code in master and ran it, and was able to reproduce the same maps as the executable. I've uploaded them here:

https://wads.doomleague.org/wdl2020.wad_MAP04_v2.svg
https://wads.doomleague.org/wdl2020.wad_MAP22_v2.svg

**Comment by devinacker** [comment]
Oh, I see what's going on, it's just missing the IWAD flats. Make sure you're including doom2.wad, e.g.:

`dmsvg doom2.wad wdl2020.wad map04`

**Comment by bcahue** [comment]
Whoops, that was indeed the issue. It was so seamless I forgot there was no way of it knowing where to find it. Thanks!
